name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: '.'
          severity: error

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Git user for tests
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Test User"
          mkdir -p "$HOME/.config/ai-rizz"
      
      - name: Run test suite
        run: make test
